blank_issues_enabled: false

contact_links:
  - name: Gaia Green Proposals
    url: https://github.com/kthecoder/GaiaGreen
    about: Please submit feature proposals on the Godot proposals repository, not here.

  - name: Gaia Green Community Channels
    url: https://aveyrin.com/discord
    about: Please ask for technical support in , not here.
